spring:
  application:
    name: sustainability-management
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/sustainability}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
    consumer:
      group-id: sustainability-management
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer

server:
  port: ${SERVER_PORT:8100}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

sustainability:
  reporting:
    periods: [MONTHLY, QUARTERLY, ANNUAL]
  carbon:
    diesel-factor-kg-co2e-per-liter: 2.68
    gasoline-factor-kg-co2e-per-liter: 2.31
    electricity-factor-kg-co2e-per-kwh: 0.92

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.paklog.sustainability: DEBUG
