apiVersion: v2
name: sustainability-management
description: Carbon tracking and ESG reporting
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
- paklog
- warehouse
- wms
- microservices
maintainers:
- name: Paklog Team
